postmanlabs/postman-code-generators

codegens/csharp-restsharp/lib/restsharp.js, codegens/curl/lib/index.js, codegens/golang/lib/index.js, codegens/java-okhttp/lib/index.js, codegens/js-jquery/lib/js-jquery.js, codegens/nodejs-native/lib/request.js, codegens/ocaml-cohttp/lib/ocaml.js, codegens/php-curl/lib/php-curl.js, codegens/python-requests/lib/python-requests.js, codegens/ruby/lib/ruby.js, codegens/swift/lib/swift.js
changed default indentCount in various codegens to match with what acttually is being used in generating snippet
=> Corrected indenntCount defaults

codegens/nodejs-native/lib/parseRequest.js, codegens/nodejs-native/test/unit/fixtures/testcollection/collection.json, codegens/nodejs-native/test/unit/snippet.test.js
Fixed a bug where query params were ignored if the url provided has no path [GitHub#5274]
=> Fixed a bug were query params were ignored if the url provided has no path

codegens/nodejs-request/lib/parseRequest.js, codegens/nodejs-request/test/unit/snippet.test.js, codegens/powershell-restmethod/lib/index.js, codegens/powershell-restmethod/test/unit/convert.test.js
Codegens changed :
- nodejs-request
- powershell-restmethod
=> Fixed failing snippet generation for file body type

codegens/shell-httpie/package.json, test/codegen/structure.test.js
Added syntax_mode to shelll-httpie.
Added structure test at common repo level for same.
=> Syntax mode test and fixes

codegens/nodejs-native/lib/request.js
Removed the comment stating maximum redirects allowed
=> Nodejs-Native follow redirects comment fix

codegens/csharp-restsharp/lib/restsharp.js, codegens/csharp-restsharp/test/unit/convert.test.js
- Added support for followRedirects options.
- Added failing test for the same.
=> Csharp-RestSharp follow redirects fix

codegens/libcurl/lib/index.js, codegens/libcurl/package.json, codegens/libcurl/test/unit/convert.test.js
- Updated package json to have language as C and variant as libcurl.
-  Added support for includeBoilerplate option.
- Fixed various indentation issues.
=> Libcurl fixes

codegens/js-fetch/lib/index.js, codegens/js-fetch/test/unit/convert.test.js, codegens/js-fetch/test/unit/fixtures/testcollection/collection.json
- Fixed sanitization of single quoted header keys and values.
- Fixed generating code snippet when no body is provided in request json
=> Javascript-Fetch fixes

codegens/js-xhr/lib/index.js, codegens/js-xhr/test/unit/fixtures/testcollection/collection.json, codegens/libcurl/lib/index.js, codegens/libcurl/test/unit/fixtures/testcollection/collection.json, codegens/powershell-restmethod/lib/index.js, codegens/powershell-restmethod/test/unit/convert.test.js, codegens/powershell-restmethod/test/unit/fixtures/testcollection/collection.json
Codegens corrected :
- js xhr
- powershell
- libcurl
=> Handled proper header sanitisation

codegens/nodejs-request/lib/request.js, codegens/nodejs-request/test/unit/snippet.test.js
This pull request fixes issue #63
=> Fixed removal of extra comma/s when requestTimeout is set in nodejs request

codegens/nodejs-unirest/lib/unirest.js, codegens/nodejs-unirest/test/unit/fixtures/testcollection/collection.json
Updated nodejs-unirest snippet for handling error. 
Removed VIEW request.
=> Removed VIEW request

codegens/csharp-restsharp/lib/restsharp.js, codegens/golang/lib/index.js, codegens/http/lib/code-http-converter.js, codegens/java-okhttp/lib/okhttp.js, codegens/java-unirest/lib/unirest.js, codegens/js-fetch/lib/index.js, codegens/js-jquery/lib/js-jquery.js, codegens/js-xhr/lib/index.js, codegens/js-xhr/test/unit/convert.test.js, codegens/libcurl/lib/index.js, codegens/nodejs-native/lib/request.js, codegens/nodejs-request/lib/request.js, codegens/nodejs-unirest/lib/unirest.js, codegens/ocaml-cohttp/lib/ocaml.js, codegens/php-curl/lib/php-curl.js, codegens/php-pecl-http/lib/phpPecl.js, codegens/php-pecl-http/test/unit/converter.test.js, codegens/powershell-restmethod/lib/index.js, codegens/python-http.client/lib/python-httpclient.js, codegens/python-requests/lib/python-requests.js, codegens/ruby/lib/ruby.js, codegens/swift/lib/swift.js
For consistency with app/newman default behavior
=> Changed default value of option trimRequestBody to false. 

codegens/php-pecl-http/lib/phpPecl.js, codegens/php-pecl-http/test/unit/converter.test.js
=> Removed the script closing tag in php/pecl_http

codegens/csharp-restsharp/lib/parseRequest.js, codegens/libcurl/lib/index.js, codegens/powershell-restmethod/lib/index.js
in: 
csharp-restsharp
libcurl
powershell
Test case added to common newman test.
=> Checking request.body before using request.body.toJSON().

codegens/nodejs-native/lib/parseRequest.js, codegens/nodejs-native/lib/request.js, codegens/nodejs-native/test/unit/snippet.test.js, codegens/python-http.client/lib/python-httpclient.js, codegens/python-http.client/test/unit/converter.test.js, codegens/shell-httpie/lib/shell-httpie.js, codegens/shell-httpie/lib/util/helpers.js, codegens/shell-httpie/test/unit/converter.test.js
Languages changed:
- nodejs-native
- python-http.client
- shell httpie
=> Fixed the snippets which ignored port in the code generation

codegens/java-okhttp/lib/parseRequest.js, codegens/nodejs-unirest/lib/parseRequest.js, codegens/nodejs-unirest/lib/unirest.js, test/codegen/newman/fixtures/testCollection.json
The & character needs to be escaped as it is being used to separate two different keys
=> Added escaping of & in urlencode keys and values

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md
Added possible templates which can be a part of the issue filing.
=> Issue templates

npm/test.sh, test/codegen/newman/fixtures/basicCollection.json, test/codegen/newman/fixtures/formdataFileCollection.json, test/codegen/sanity/sanity.test.js
Sanity snippet generation tests for all codegens
=> Sanity snippet generation tests for all codegens

npm/ci-requirements.sh
Fix for HashSum mismatch on travis.
=> Fix for HashSum mismatch

.github/ISSUE_TEMPLATE/Pull_request.md
**What it does**
This PR fixes issue #182 by adding template for creating a pull request.
**Changes I made**
- Created a **`Pull_request.md`** file containing the template for PR in `.github` directory.
**Screenshot**
**Follow Up**
`N/A`
@shreys7  Please review!
=> Added PR template

CONTRIBUTING.md, README.md, codegens/http/README.md, codegens/java-okhttp/README.md, codegens/java-unirest/README.md, codegens/js-fetch/README.md, codegens/js-jquery/README.md, codegens/js-xhr/README.md, codegens/libcurl/README.md, codegens/nodejs-request/README.md, codegens/objective-c/README.md, codegens/ocaml-cohttp/README.md, codegens/php-httprequest2/README.md, codegens/php-pecl-http/README.md, codegens/powershell-restmethod/README.md, codegens/python-http.client/README.md, codegens/shell-httpie/README.md, codegens/swift/README.md, lib/index.js
**What this PR does**
This PR fixes the spelling mistakes that have been unknowingly left while development.
**Changes you made**
- Modified few sample code which were provided as an example.
- Fixed typos throughout the repository.
**Screenshot/ CodeSnippet**
N/A
**Test Configuration**:
N/A
**Follow up**
N/A
*Thanks for contributing!* ❤️
=> Fixed example code and removed typos throughout the repo

README.md
Added nodejs axios in the readme.
=> updates readme to include nodejs axios

codegens/nodejs-axios/lib/axios.js, codegens/nodejs-axios/lib/parseRequest.js
- Add arrow function syntax
- `let` declaration syntax for config, data, etc. objects
=> Fix ES6 handling in Axios

CHANGELOG.md, package-lock.json, package.json
Changelog and version bump v1.0.2
=> Changelog and version bump v1.0.2

codegens/python-http.client/lib/python-httpclient.js, codegens/python-http.client/lib/util/parseBody.js, codegens/python-http.client/test/unit/converter.test.js, npm/addPathToFormdataFile.js, npm/test.sh, test/codegen/newman/fixtures/formdataFileCollection.json
Fixes #366.
Before:
```
import http.client
import mimetypes
conn = http.client.HTTPSConnection("postman-echo.com")
dataList = []
boundary = 'wL36Yn8afVp8Ag7AmP8qZ0SA4n1v9T'
dataList.append('--' + boundary)
dataList.append('Content-Disposition: form-data; name=ankit; filename={0}'.format('ques.2.jpeg'))
fileType = mimetypes.guess_type('test.jpeg')[0] or 'application/octet-stream'
dataList.append('Content-Type: {}'.format(fileType))
dataList.append('')
with open('test.jpeg') as f:
dataList.append(f.read())
dataList.append('--'+boundary+'--')
dataList.append('')
body = '\r\n'.join(dataList)
payload = body
headers = {
'Content-type': 'multipart/form-data; boundary={}'.format(boundary) 
}
conn.request("POST", "/post", payload, headers)
res = conn.getresponse()
data = res.read() …
```
=> Add support for uploading binary files for multipart/form-data bodies in python-http.client.

codegens/curl/lib/util.js, codegens/golang/lib/util.js, codegens/js-fetch/lib/util.js, codegens/js-xhr/lib/util.js, codegens/libcurl/lib/util.js, codegens/nodejs-axios/lib/util.js, codegens/nodejs-request/lib/util.js, codegens/objective-c/lib/util.js, package-lock.json, package.json, test/codegen/newman/fixtures/basicCollection.json
=> Sanitize \r in request body.

codegens/golang/lib/index.js, codegens/js-xhr/lib/index.js, codegens/libcurl/lib/index.js, codegens/ocaml-cohttp/lib/util.js, codegens/php-curl/lib/util/sanitize.js, codegens/powershell-restmethod/lib/index.js, codegens/python-http.client/lib/util/sanitize.js, codegens/python-http.client/test/newman/newman.test.js, codegens/python-requests/lib/util/sanitize.js, codegens/python-requests/test/newman/newman.test.js, codegens/ruby/lib/util/sanitize.js, codegens/swift/lib/util.js, test/codegen/newman/fixtures/basicCollection.json
=> Use encodeURIComponent instead of escape for urlencoded request body

codegens/http/lib/code-http-converter.js, codegens/http/lib/util.js, codegens/http/test/unit/converter.test.js, codegens/swift/test/newman/newman.test.js
=> Parse url manually instead of taking host and path from the request.

codegens/curl/lib/index.js, codegens/curl/test/unit/convert.test.js
=> Add ` as line continuation delimiter for curl

npm/deepinstall.js
=> Use quotes for prepackagePath in deepinstall.js

codegens/js-fetch/lib/index.js, codegens/js-fetch/test/unit/convert.test.js, codegens/js-jquery/lib/util/parseBody.js, codegens/js-jquery/test/unit/converter.test.js, codegens/js-xhr/lib/index.js, codegens/js-xhr/test/unit/convert.test.js, codegens/nodejs-axios/lib/parseRequest.js, codegens/nodejs-axios/test/unit/snippet.test.js, codegens/nodejs-native/lib/parseRequest.js, codegens/nodejs-native/test/unit/snippet.test.js, codegens/nodejs-request/lib/parseRequest.js, codegens/nodejs-request/test/unit/snippet.test.js, codegens/nodejs-unirest/lib/parseRequest.js, codegens/nodejs-unirest/test/unit/snippet.test.js
Fixes https://github.com/postmanlabs/postman-app-support/issues/8635
=> Use Json.parse for all json like application types

codegens/curl/lib/index.js, codegens/curl/lib/util.js, codegens/curl/test/unit/convert.test.js
=> Use quoteType everywhere in curl, not just in the url

codegens/nodejs-axios/lib/parseRequest.js
=> Add proper indentation in nodejs-axios when bodytype is urlencoded

codegens/csharp-restsharp/lib/parseRequest.js, codegens/curl/lib/index.js, codegens/dart-http/lib/index.js, codegens/golang/lib/index.js, codegens/http/lib/util.js, codegens/java-okhttp/lib/parseRequest.js, codegens/java-unirest/lib/parseRequest.js, codegens/nodejs-axios/lib/parseRequest.js, codegens/nodejs-native/lib/parseRequest.js, codegens/nodejs-request/lib/parseRequest.js, codegens/nodejs-unirest/lib/parseRequest.js, lib/index.js
Add proper handling for query and variables of graphql body
=> Add proper handling for query and variables of graphql body

.gitignore
=> chore: add additional entry for dummyBinaryFile

codegens/python-requests/lib/util/parseBody.js
Add space around assignment `=` as per [pep8](https://pep8.org/#other-recommendations)
=> Chore: PEP8 python-requests

CHANGELOG.md, codegens/kotlin-okhttp/npm-shrinkwrap.json, codegens/nodejs-native/npm-shrinkwrap.json, package-lock.json, package.json
=> Releasing v1.7.0

CHANGELOG.md, lib/assets/languageLabels.json, npm/test.sh, package-lock.json, package.json, test/unit/lib.test.js
Adding language labels for new languages.
=> Release v1.7.1

codegens/http/npm-shrinkwrap.json, codegens/nodejs-native/npm-shrinkwrap.json, codegens/nodejs-native/package.json, codegens/python-http.client/package-lock.json, codegens/python-http.client/package.json
This PR bumps up `postman-collection` module version to latest ins some of the individual codegen's `package.json` file.
=> Bumped up postman-collection sdk to v4.4.0.

codegens/curl/lib/index.js, codegens/curl/test/unit/convert.test.js
=> [Fix/issue#540] Curl codesnippet's JSON body must follow multiLine option's configuration

CHANGELOG.md
- Adding changes to CHANGELOG.md for the new release.
=> Updated Changelog for v1.14.0
