codegens/python-http.client/lib/python-httpclient.js
codegens/python-http.client/test/unit/converter.test.js

- Removed followRedirect option as it doesn't handle redirects.
- Fixed a bug which caused snippet generation to fail when request url provided is empty.
- Added failing test for the empty url request.

Python-http.client fixes

---

codegens/python-http.client/lib/python-httpclient.js
codegens/python-http.client/test/unit/converter.test.js

Fixed a bug which failed snippet generation when body mode is formdata with non zero headers

Fixed formdata header bug in python-http.client

---

codegens/curl/lib/index.js
codegens/curl/lib/util.js
codegens/curl/test/unit/convert.test.js
codegens/java-unirest/lib/parseRequest.js
codegens/java-unirest/lib/unirest.js
codegens/java-unirest/test/unit/convert.test.js
codegens/ruby/test/unit/converter.test.js
codegens/swift/lib/swift.js
codegens/swift/lib/util.js
codegens/swift/test/unit/convert.test.js

Some of the codegens doesn't encode url on its own and fails to run if not encoded.
For such codegens, we have decided to encode everything in the url other than the unresolved variables
Languages affected: 
- curl
- swift
- java-unirest

Addressed unresolved variable encoding issues

---

codegens/nodejs-request/lib/request.js
codegens/nodejs-request/test/unit/snippet.test.js

The line `var fs = require(''fs);` was being added in the snippet even when fs was not required at all. fs is only used to upload a file via form-data

Removed unused require('fs') for nodejs-request

---

codegens/swift/lib/swift.js
codegens/swift/lib/util.js

Details: 
For sending the form data parameters, we used to form a swift dictionary from the request body JSON that we get from request object.
the code used was: `sanitize(JSON.stringify(body, null, 4), mode, trim)`
and sanitize for form data was: `inputString.replace(/{/g, '[').replace(/}/g, ']')`
Sanitize had this code because the swift dictionary used `[` and `]`.
Two problems:
1. Hardcoding paramater as 4 in `JSON.stringify()` doesn't take into account the indentation option we provide.
2. If parameter key or value contains a `[` or `]` , it was being replaced by `{` and `}` respectively.
Fixed the issue by manually parsing the request body to form the swift dictionary accordingly

Removed changing of { to [ everywhere inside formdata JSON body to convert it to swift dictionary

---

codegens/ocaml-cohttp/lib/ocaml.js
codegens/python-requests/lib/python-requests.js

- Removed addition of content-type header twice for binary file upload in ocaml
- indentation fixes in python-requests headers

General bugfixes in 0.0.11

---

codegens/shell-httpie/lib/util/helpers.js
codegens/shell-httpie/lib/util/sanitize.js

multipart/form-data
- Using  --form, -f option ensures that data fields are serialized as, and Content-Type is set to, application/x-www-form-urlencoded; charset=utf-8. 
- If one or more file fields is present, the serialization and content type is multipart/form-data
- docs: https://httpie.org/doc#regular-forms
Thus it is not possible to send non-file fields in httpie using multipart/form-data.
special character in raw text
- It used to fail because we use printf 'raw data' and then pipe it to httpie, which is the only way to post raw data using it. But % is interpreted as special character when used with printf, hence added the logic to escape %, i.e. use `%%` instead of `%`
urlencoded
- It supports x-www-form-urlencoded data

Added support for using special characters in raw body mode in shell-httpie

---

codegens/java-unirest/lib/parseRequest.js
codegens/java-unirest/test/unit/convert.test.js

Java-unirest by default sends the form data parameters as x-www-form-urlencoded if there are no file fields present. After java-unirest 2.1, they have added a method name .multiPartContent() that forces the fields to be sent as multipart/form-data even if there are not file fields present.
Added the above fix and added the corresponding unit tests.

Java-unirest formdata fix and tests

---

codegens/http/lib/util.js
codegens/http/test/unit/converter.test.js

- Create a GET request with no body. Save it to a collection and click view in web. It fails to generate snippets for HTTP.
- It fails for all the requests where no body is present.
- The following function tries to access request.body.mode without having a check for the body field to be present:
```function getHeaders (request) {
let contentTypeIndex = _.findIndex(request.headers.members, { key: 'Content-Type' }),
formDataHeader = `multipart/form-data; boundary=${FORM_DATA_BOUNDARY}`,
headers = '';
if (contentTypeIndex >= 0) {
if (request.headers.members[contentTypeIndex].value === 'multipart/form-data' || request.body.mode === 'formdata') {
request.headers.members[contentTypeIndex].value = formDataHeader;
}
}
_.forEach(request.headers.members, (header) => {
header.key = …
```

Fixed failing code generation in http for requests without body

---

codegens/js-jquery/lib/js-jquery.js
codegens/js-jquery/test/unit/converter.test.js

Multiple headers with the same name caused creating an invalid snippet, because of the same keys in an object. The headers with the same name will be clubbed and kept in an array, i.e.
```"sdf": ["sdf", "sdsfg"]```
This fixes #124

Fixed multiple headers with same name issue in js-jquery

---

codegens/js-fetch/lib/index.js
codegens/js-fetch/test/unit/convert.test.js
codegens/nodejs-native/lib/parseRequest.js
codegens/nodejs-native/test/unit/snippet.test.js
codegens/nodejs-unirest/lib/unirest.js
codegens/nodejs-unirest/test/unit/snippet.test.js
codegens/powershell-restmethod/lib/index.js
codegens/powershell-restmethod/test/unit/convert.test.js
codegens/shell-wget/lib/shell-wget.js
codegens/shell-wget/lib/util/sanitize.js
codegens/shell-wget/test/unit/converter.test.js
test/codegen/newman/fixtures/basicCollection.json

Need escaping of single/double quotes in url as query params can contain them. 
This PR fixes #132. 
Added the fixes in following codegens:
- nodejs-native
- nodejs-unirest
- javascript-fetch
- shell-wget
- powershell-restmethod
Added regression test for the same in basicCollection.

Sanitisation of single/double quotes in url

---

codegens/ocaml-cohttp/lib/ocaml.js

Snippet doesn't compile with unused `rest` command. Snippet should now be:
```ocaml
let reqBody =
let uri = Uri.of_string "https://api.twitter.com/labs/1/users?usernames=TwitterDev&format=detailed" in
Client.call ~headers:headers `GET uri >>= fun (_resp, body) ->
body |> Cohttp_lwt.Body.to_string >|= fun body -> body
```

ignore unused `resp` variable on line 392

---

npm/addPathToFormdataFile.js
npm/ci-requirements.sh
npm/test.sh

Previously, the files required for testing form data file uploads were created using `ci-requirements.sh` step. This file is not run locally and hence would cause form-data tests to fail locally. This step has been removed from `ci-requirements.sh` file and moved to `test.sh` file.
This fixes #172

Move test file creation step from ci-requirements script to test script for form data testing

---

codegens/csharp-restsharp/lib/parseRequest.js
codegens/csharp-restsharp/test/unit/convert.test.js
codegens/csharp-restsharp/test/unit/fixtures/testUA.json

I fixed issue #158 by changing the C# RestSharp API .
As He says, the 
```c#
request.AddHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0");
```
doesn't work and will be overwritten to a default UA, the official solution is to use 
```C#
client.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0";
```
Instead of Add Header.
So I just fix it by checking whether a Header's key equals to `User-Agent`, If so, output the `client.UserAgent = "..."`, otherwise, output the `request.AddHeader(..., ...)`.
So It will work and fix the issues.
@shreys7 I added an extra unit test for my fix. This is my first time contributing to the open source community, thank you for your guidance!

Fix csharp-restsharp user agent header issue

---

codegens/nodejs-request/lib/request.js
codegens/nodejs-request/test/newman/newman.test.js
codegens/nodejs-request/test/unit/snippet.test.js
package-lock.json
test/codegen/structure.test.js

**What it does**
It allows the user to generate the code snippet for NodeJS Request in ES6 format.
This is in response to issue #115 requested by one of the users.
**Changes I made**
- Registered a new parameter ES6_enabled in **`options()`** which allows the user to toggle between whether codegen generates snippet with ES6 features or not.
- By default ES6_enabled is set to `false`
- Also added the new created option parameter in **`structure.test.js`** file to register it as a valid option id.
- Added unit tests to verify the generated snippets.
**Follow Up**
This PR is first in the series of upcoming PRs which will add the feature of generating code snippet in ES6 notation with NodeJS.

Added ES6 feature support to NodeJS-Request codegen

---

codegens/nodejs-unirest/README.md
codegens/nodejs-unirest/lib/unirest.js
codegens/nodejs-unirest/test/newman/newman.test.js
codegens/nodejs-unirest/test/unit/snippet.test.js
test/codegen/structure.test.js

**What this PR does**
It allows the user to generate the code snippet for NodeJS Unirest in the ES6 format.
This is in response to issue #115  requested by one of the users.
**Changes you made**
- Registered a new parameter ES6_enabled in **`options()`** which allows the user to toggle between whether codegen generates snippet with ES6 features or not.
- By default ES6_enabled is set to `false`
- Also added the newly created option parameter in **`structure.test.js`** file to register it as a valid option id.
- Added unit tests to verify the generated snippets in **snippet.test.js**
- Added a new mocha test suite to verify that the generated snippet is runnable in **newman.test.js.**
- Updated the **readme.md** file with new option parameter.
**Screenshot/ CodeSnippet**
Not required …

Added ES6 feature support to NodeJS Unirest codegen

---

codegens/nodejs-native/README.md
codegens/nodejs-native/lib/request.js
codegens/nodejs-native/test/newman/newman.test.js
codegens/nodejs-native/test/unit/snippet.test.js
test/codegen/structure.test.js

**What this PR does**
It allows the user to generate the code snippet for NodeJS Native in ES6 format.
This is in response to issue #115  requested by one of the users.
**Changes you made**
- Registered a new parameter ES6_enabled in **`options()`** which allows the user to toggle between whether codegen generates snippet with ES6 features or not.
- By default ES6_enabled is set to `false`
- Also added the newly created option parameter in **`structure.test.js`** file to register it as a valid option id.
- Added unit tests to verify the generated snippets in **snippet.test.js**
- Added a new mocha test suite to verify that the generated snippet is runnable in **newman.test.js.**
- Updated the **readme.md** file with new option parameter.
**Screenshot/ CodeSnippet**
Not required
**Test …

Added ES6 feature support to NodeJS Native codegen

---

codegens/curl/test/newman/newman.test.js
codegens/java-okhttp/test/newman/newman.test.js
codegens/ruby/lib/ruby.js
codegens/shell-httpie/lib/shell-httpie.js
codegens/shell-httpie/test/unit/converter.test.js
test/codegen/newman/fixtures/basicCollection.json
test/codegen/newman/newmanTestUtil.js

- Skipped java-okhttp newman tests
- Added `x-amzn-trace-id` to the list of headers to delete while comparing responses with newman
- Changed `DELETE` request call from postman-echo to mockbin.org
- Changed protocol from `http` to `https` for POST graphql bodies request
-  Added handling for GraphQL and binary file modes for URLs starting with `https` in Ruby
- Added handling for `https` protocol in shell httpie

Fix failing CI tests

---

codegens/js-jquery/lib/js-jquery.js
codegens/js-jquery/test/unit/converter.test.js
codegens/powershell-restmethod/lib/index.js
codegens/powershell-restmethod/test/unit/convert.test.js

**Affected codegens**
- js-jquery
- powershell-restmethod
**RCA**
- The code generator throws the following error:
```
TypeError: Cannot read property 'split' of undefined
```
- We use src.split to get the filename from the path of the file stored in formParam.src field
- This problem is seen in older collection versions, where the type parameter is not present in form-data parameters. The way we generate code for form params is as following:
```
if (value.type === 'text') {
return (`form.append("${sanitize(value.key, request.body.mode, trimRequestBody)}", "` +
`${sanitize(value.value, request.body.mode, trimRequestBody)}");`);
}
var pathArray = value.src.split(path.sep),
fileName = pathArray[pathArray.length - 1];
return (`form.append("${sanitize(value.key, request.body.mode, …
```

Fixed a bug which caused snippets generation to fail for form data params with no type key present

---

codegens/curl/lib/util.js
codegens/curl/test/unit/convert.test.js
codegens/java-unirest/lib/parseRequest.js
codegens/java-unirest/test/unit/convert.test.js
codegens/nodejs-native/lib/parseRequest.js
codegens/nodejs-native/test/unit/snippet.test.js
codegens/python-http.client/lib/python-httpclient.js
codegens/python-http.client/test/unit/converter.test.js
codegens/swift/lib/util.js
codegens/swift/test/unit/convert.test.js

Fixes https://github.com/postmanlabs/postman-app-support/issues/8674
Single/double quotes were not handled correctly in some of the languages.
Languages affected:
- cURL
- Java Unirest
- NodeJS Native (path)
- Python http.client
- Swift

Add sanitising of quotes in URLs(and paths)

---

codegens/python-requests/lib/python-requests.js
codegens/python-requests/lib/util/parseBody.js
codegens/python-requests/test/unit/converter.test.js

Removes the spaces surrounding the keyword arguments, as per PEP 8 style guide for unannotated function parameters.
https://www.python.org/dev/peps/pep-0008/
Python - Requests code snippet was:
`response = requests.request("GET", url, headers=headers, data = payload, allow_redirects = False)`
now becomes:
`response = requests.request("GET", url, headers=headers, data=payload, allow_redirects=False)`

Python - Requests Keyword Arguments

---

codegens/http/README.md

Changed the type of output from ```cURL``` into ```RAW HTTP request``` in the README file of codegens/http folder.
I felt this is a minor change so didn't open an issue for this

Fix the type of output for http codegen docs

---

codegens/golang/lib/index.js
codegens/golang/lib/util.js

This is random, but when looking up documentation for the [CyberSource REST API](https://developer.cybersource.com/api-reference-assets/index.html#payments_payments_process-a-payment) I randomly came across [these Postman docs](https://documenter.getpostman.com/view/2960117/S17m1riA?version=latest#6365de64-d3f7-45ff-bb98-1a5efe4df79e).  (How do such docs even come into being?...)
When I changed the language to `Go - Native`, what do I behold?
```go
// ...
payload := strings.NewReader("{
\n  	\"clientReferenceInformation\": {
\n  		\"code\": \"test_payment\"
\n  	},
\n  	\"processingInformation\": {
\n  		\"commerceIndicator\": \"internet\"
\n  	},						
\n  	\"orderInformation\": {
\n  		\"billTo\": {	
\n  			\"firstName\": \"John\",
\n  			\"lastName\": \"Doe\",
\n  			\"address1\": \"1 …
```

Go: Use Multiline Strings for Raw Bodies

---

codegens/python-requests/lib/python-requests.js

Fixes #249
RCA
This issue was due to different versions of python. In python 2.x, byte strings are printed without any prefix/suffix unlike the case in python 3.x where resulting byte code is inside `b' string here '`.
Solution
Removing encoding solves the above issue.
This PR adds the following changes:
- removes .encode(utf8) from print statement in generated snippet

Removes utf8 encoding from generated snippet (python-requests)

---

codegens/golang/lib/index.js
codegens/golang/test/unit/convert.test.js

Fixes: https://github.com/postmanlabs/postman-app-support/issues/8318 partially
The err due to absence of `err` check is caused by go vet(kind of linting for go), which forces strict formatting, this includes checking for err being nil or not  if we have assigned some value to `err`. 
So basically if anyone uses go vet then `err` checking is mandatory if it has been assigned:
`if err!=nil {
//do something
}
`
- adds err check after client.Do(req)
- adds println and return statement inside err condition body

Adds snippet to check err before using res in GoNative

---

codegens/swift/lib/swift.js

In the guarded fail case the semaphore wasn't being signaled and thus the 'program' would lock up.
Added a `semaphore.signal()` to the guard body

Signal the semaphore on a fail case as well

---

codegens/nodejs-request/lib/parseRequest.js

Previously the generated snippet with raw body had double quote wrapping. This pr changes it to single quote to have consistency in quotes throughout the generated snippet.
Changes:
- removes json.stringify where not necessary
- sanitize raw body

Replaces double quote to single quote for body params

---

codegens/nodejs-axios/lib/parseRequest.js
codegens/nodejs-native/lib/parseRequest.js
codegens/nodejs-request/lib/parseRequest.js
codegens/nodejs-unirest/lib/parseRequest.js

Update NodeJs GraphQL query to support multiline string

---

codegens/php-curl/lib/php-curl.js
codegens/php-curl/lib/util/parseBody.js
codegens/php-curl/lib/util/sanitize.js
codegens/php-curl/test/unit/converter.test.js
test/codegen/newman/fixtures/basicCollection.json

Solves #284 
PHP expands variables and escape sequences for special characters inside double-quotes. This is a problem if body of a request contains `$` sign. Using single-quotes solves this problem. This is an alternative solution to #285 .

Replace double-quotes by single-quotes in codegen/php-curl

---

codegens/swift/lib/swift.js
codegens/swift/test/newman/newman.test.js
npm/ci-requirements.sh

Add optional import of FoundationNetworking in swift codegen to make it work with Swift 5.x

---

codegens/python-requests/test/newman/newman.test.js

Currently the tests are only running for Python 2 in the `python-requests` codegen. I have enabled them for both 2 and 3. `python-http.client` is Python 3 only, so there was no need for it in that.

Run tests for both Python 2 and Python 3 for python-requests

---

codegens/python-requests/lib/util/parseBody.js
codegens/python-requests/test/unit/converter.test.js

Fixes #247 
- Adds ContentTypetoHeader map
- Adds snipept for content type
- Modifies test for `no file in formdata`

Adds ContentType to python snippets for multipart/formdata

---

codegens/curl/lib/index.js
codegens/curl/lib/util.js
codegens/curl/test/unit/convert.test.js
npm/ci-requirements.sh

fixes #257 
Curl requires form data to be enclosed in double quotes if form data value contains semicolon or comma
This PR adds check for the above conditions and adds the following changes 
- adds check for semicolon and comma in form data
- encloses form data value if semicolon/comma is present
- Modifies sanitize function, adds follows
- adds option to escape double quotes
- adds option to escape back slash

Fixes issue with semicolon in form data (CURL)

---

codegens/curl/lib/index.js
codegens/curl/test/unit/convert.test.js
codegens/golang/lib/index.js
codegens/golang/test/unit/convert.test.js
codegens/http/lib/util.js
codegens/http/test/unit/converter.test.js
codegens/java-okhttp/lib/parseRequest.js
codegens/java-okhttp/test/unit/convert.test.js
codegens/java-unirest/lib/parseRequest.js
codegens/java-unirest/test/unit/convert.test.js
codegens/libcurl/lib/index.js
codegens/libcurl/test/unit/convert.test.js
codegens/nodejs-axios/lib/parseRequest.js
codegens/nodejs-axios/test/unit/snippet.test.js
codegens/nodejs-native/lib/parseRequest.js
codegens/nodejs-native/test/unit/snippet.test.js
codegens/ocaml-cohttp/lib/ocaml.js
codegens/ocaml-cohttp/test/unit/convert.test.js
codegens/powershell-restmethod/lib/index.js
codegens/powershell-restmethod/test/unit/convert.test.js
codegens/python-http.client/lib/util/parseBody.js
codegens/python-http.client/test/unit/converter.test.js
codegens/swift/lib/swift.js
codegens/swift/test/unit/convert.test.js

Fixes https://github.com/postmanlabs/postman-app-support/issues/8736
Support has been added for the following codegens:
* Curl
* Go
* HTTP
* Java - OkHttp
* Java - Unirest
* Libcurl
* Nodejs - Axios
* Nodejs - Native
* Powershell
* Python - http.client
* Swift
* Ocaml
The rest we couldn't support the following because there is no way to add Content-Type for these :
* Javascript - All the codegens use `FormData` api, which does not support content-type for form fields
* Nodejs - Unirest and Request
* All the PHP codegens - they use associative arrays to store formdata. Didn't see how we can add Content-Type
* Ruby - Ruby uses the HTML5 spec instead of ﻿﻿RFC 7578, and it explicitly says that formdata values cannot have Content-Type
* Csharp-Restsharp
* httpie, wget, Python-requests - They …

Add Content-type for form-data fields if is present in the request.

---

codegens/curl/lib/index.js
codegens/curl/test/unit/convert.test.js

Fixes https://github.com/postmanlabs/postman-app-support/issues/9212

Add semicolon after header key in curl codegen if the value is empty string.

---

codegens/python-http.client/lib/python-httpclient.js
codegens/python-http.client/lib/util/parseBody.js
codegens/python-http.client/test/unit/converter.test.js
codegens/python-requests/lib/python-requests.js
codegens/python-requests/lib/util/parseBody.js
codegens/python-requests/test/unit/converter.test.js

Fixes #426 
Before:
```
payload="{\n    \"Hello\": \"world\",\n    \"boolean\": true,\n    \"array\": [1,2,3]\n}"
```
After:
```
payload = json.dumps({
"Hello": "world",
"boolean": True,
"array": [
1,
2,
3
]
})
```

Use json.dumps in Python codegens if Content-Type is JSON.

---

test/codegen/newman/newmanTestUtil.js

`cf-connecting-ip` is can be different in the CI for each request, while `cf-request-id`is always different. This is causing one of the newman tests to fail. Ignoring these headers fixes this.

Ignore always changing headers returned by mockbin

---

codegens/csharp-restsharp/lib/parseRequest.js
codegens/dart-http/lib/index.js

Fixes #459 
C#:
```
using RestSharp;
namespace HelloWorldApplication {
class HelloWorld {
static void Main(string[] args) {
var client = new RestClient("http://example.com");
client.Timeout = -1;
var request = new RestRequest(Method.GET);
request.AddHeader("Content-Type", "application/json");
var body = @"{" + "\n" +
@"    ""hello"": ""world""," + "\n" +
@"    ""this"": true," + "\n" +
@"    ""call"": [1,2,3,null]" + "\n" +
@"}";
request.AddParameter("application/json", body,  ParameterType.RequestBody);
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);
}
}
}
```
Dart:
```
import 'dart:convert';
import 'package:http/http.dart' as http;
void main() async {
var headers = {
'Content-Type': 'application/json'
};
var request = http.Request('GET', …
```

Add proper formatting of JSON in Dart and C#

---

codegens/java-okhttp/lib/okhttp.js

Allow GET method to have a body in java-okhttp if present in input request.

---

npm/ci-requirements.sh

Fixes the issue of CI pipeline breaking

Add Restsharp version to download in ci-requirements

---

codegens/js-xhr/lib/index.js

If a user tries send a GET request with a body or with the `Cookie` header set, the add a comment warning them that browser will strip them away before sending the request. For example:
```javascript
// WARNING: For GET requests, body is set to null by browsers.
var data = JSON.stringify({
'hello': 'world'
});
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;
xhr.addEventListener("readystatechange", function() {
if(this.readyState === 4) {
console.log(this.responseText);
}
});
xhr.open("GET", "https://postman-echo.com/get");
// WARNING: Cookies will be stripped away by the browser before sending the request.
xhr.setRequestHeader("Cookie", "cookie");
xhr.setRequestHeader("Content-Type", "application/json");
xhr.send(data);
```

Add warning comments before misleading code in JS-xhr

---

CHANGELOG.md
package-lock.json
package.json

v1.3.0 (December 16, 2022)
* Update C# restsharp codegen to support (107)[https://restsharp.dev/v107/]
* Fixes an issue where HTTP code snippet was generating wrong boundaries (11084)[https://github.com/postmanlabs/postman-app-support/issues/11084]
* Fixes an issue with Axios code snippets not including maxBodyLength param

Release v1.3.0

---

codegens/curl/lib/index.js
codegens/curl/lib/util.js
codegens/curl/test/unit/convert.test.js
test/codegen/structure.test.js

- For `HEAD`, do not add `--request`
- For `GET` only add if it has a request body and the request has body pruning is not enabled
- For `POST`, only add if there is no request body
- Add it explicitly in cases where the user has selected to follow redirects and also retain the original HTTP method while doing it
- Introduced a new option, `followOriginalHttpMethod` with the default value `false`
- We're trying to make the experience for users better by also honouring request settings as it is sometimes frustrating to tweak snippet settings in addition to request settings.
- `followOriginalHttpMethod` is also an option in request in Postman. To better enable integration with the request editor, we honour the value if present in request and fallback to options if not present.
- …

Do not add HTTP method explicitly in curl when not required

---

codegens/curl/lib/index.js
codegens/curl/test/unit/convert.test.js

Make use of  the `backSlash: true` argument in `sanitize` function for Raw bodies.
Fixes postmanlabs/postman-app-support#11049

Escape backslash character in raw bodies for curl codegen

---

codegens/curl/lib/index.js
codegens/curl/lib/util.js
codegens/curl/test/unit/convert.test.js

`-g` option was missing the long-form option equivalent. This PR adds the `--globoff` counterpart.
[Documentation](https://curl.se/docs/manpage.html) for this option:
> -g, --globoff
> This option switches off the "URL globbing parser". When you set this option, you can specify URLs that contain the letters {}[] without having curl itself interpret them. Note that these letters are not normal legal URL contents but they should be encoded according to the URI standard.

Add long form option for -g

---

codegens/powershell-restmethod/lib/index.js
codegens/powershell-restmethod/lib/util.js
codegens/powershell-restmethod/test/unit/convert.test.js
npm/ci-requirements.sh

Before:
```
$body = "{`n        `"hello`": `"Wirld`",`n        `"this`": [`n            `"that`",`n            `"`$when`",`n            `"as`"`n        ]`n    }"
```
After:
```
$body = @"
{
`"hello`": `"Wirld`",
`"this`": [
`"that`",
`"`$when`",
`"as`"
]
}
"@
````

Use multiline quotes in Powershell to simplify generated code

---

README.md

Hi, I came across #629 and found it quite helpful, but it seems like the PR is stale. Hence, I made requested changes

[README.md] added link for request object in README

---

codegens/curl/lib/util.js
codegens/curl/test/unit/convert.test.js
codegens/golang/lib/index.js
codegens/golang/lib/util.js
codegens/java-okhttp/lib/okhttp.js
codegens/java-okhttp/test/newman/newman.test.js
codegens/java-okhttp/test/unit/convert.test.js
codegens/java-unirest/lib/parseRequest.js
codegens/java-unirest/lib/unirest.js
codegens/java-unirest/test/newman/newman.test.js
codegens/java-unirest/test/unit/convert.test.js
codegens/js-xhr/lib/index.js
codegens/js-xhr/lib/util.js
codegens/libcurl/lib/index.js
codegens/libcurl/lib/util.js
codegens/nodejs-native/test/newman/newman.test.js
codegens/objective-c/test/newman/newman.test.js
codegens/ocaml-cohttp/lib/ocaml.js
codegens/ocaml-cohttp/lib/util.js
codegens/php-curl/lib/php-curl.js
codegens/php-curl/lib/util/sanitize.js
codegens/python-http.client/test/newman/newman.test.js
codegens/swift/lib/util.js
codegens/swift/test/unit/convert.test.js
test/codegen/newman/fixtures/queryParamsCollection.json

As part of https://github.com/postmanlabs/postman-code-generators/pull/638, we moved the encoding to the modules, which led to double encoding.
The fix would be to remove double encoding and make this fix in all other modules as well which are now doing double encoding of `%`.

Fix an issue where % was getting double encoded in query params

---

CHANGELOG.md
codegens/swift/lib/swift.js
codegens/swift/test/unit/convert.test.js

- In postman-app-support, [Issue #10139](https://github.com/postmanlabs/postman-app-support/issues/10139) The user has described an issue they were facing with `Swift` code generated for `Content-Type` `multipart/form-data`.
- When the user was using the generated Swift code for uploading a `.MOV` video file, they were facing an issue on reaching this line:-
`let fileContent = String(data: fileData, encoding: .utf8)!`
- On analysis, it is found that the error is arising because the generated code is trying to encode video data in `UTF-8` format to be converted into `String` type, but we must realise every character in `fileData` would not be encodable in `UTF-8` format.
- Instead of converting file data to `String` type, we will change the `body` variable from `String` to `Data` type. …

[GITHUB-10139][Fix] Generated Swift code not working for multipart/form-data video upload

---

codegens/js-fetch/README.md
codegens/js-fetch/lib/index.js
codegens/js-fetch/test/unit/convert.test.js

Fixes #390.
Also updating request timeout to properly use an AbortController signal.
Sample output with `asyncAwaitEnabled` set to `true`:
```js
const myHeaders = new Headers();
myHeaders.append("my-sample-header", "Lorem ipsum dolor sit amet");
myHeaders.append("not-disabled-header", "ENABLED");
const requestOptions = {
method: "GET",
headers: myHeaders,
redirect: "follow"
};
try {
const response = await fetch("https://mockbin.org/request", requestOptions);
const result = await response.text();
console.log(result)
} catch(error) {
console.error(error);
};
```
Sample output with `asyncAwaitEnabled` set to `true` and `requestTimeout` set to `3000`:
```js
const controller = new AbortController();
const timerId = setTimeout(() => controller.abort(), 3000);
const myHeaders = new Headers(); …
```

Updating js-fetch code to have an asyncAwaitEnabled option.

---

codegens/libcurl/lib/index.js
codegens/libcurl/test/unit/convert.test.js
test/codegen/newman/fixtures/basicCollection.json
test/codegen/newman/fixtures/redirectCollection.json

- Issue: https://github.com/postmanlabs/postman-app-support/issues/12578

[FIX] libcurl: Free up headers list to prevent memory leak

---

codegens/curl/lib/util.js
codegens/curl/test/unit/convert.test.js
codegens/powershell-restmethod/lib/index.js
codegens/powershell-restmethod/lib/util.js
codegens/powershell-restmethod/test/unit/convert.test.js
codegens/ruby/lib/util/parseBody.js
codegens/ruby/lib/util/sanitize.js
codegens/ruby/test/unit/converter.test.js

- Escape special characters to preserve their literal meaning within double quotes

Escape special characters in codegen

---

codegens/curl/lib/index.js
codegens/curl/lib/util.js
codegens/curl/test/unit/convert.test.js

This PR adds support for NTLM Authentication for cURL snippet generated by adding corresponding auth information. 
Solves: https://github.com/postmanlabs/postman-code-generators/issues/254
More resources on how requests with NTLM as Auth work with cURL are mentioned below.
- https://curl.se/docs/manpage.html#--ntlm
- https://www.tsmean.com/articles/soap/how-to-call-a-soap-webservice-with-curl-and-ntlm-authentication/

Added support for NTLM auth support in cURL codegen.

---

codegens/golang/lib/index.js

This PR fixes one of a missed declaration removal that was introduced with https://github.com/postmanlabs/postman-code-generators/pull/721
i.e. Since we're now declaring `io` at global level, we don not need to redeclare it for input type of file specifically. Tests that were failing were due to this reason.

Fixed an issue where io package was declared twice.

---

npm/ci-requirements.sh
npm/deepinstall.js

- Added Proper Installation Support for Various Node Package Managers and versions.
- Added Support for `yarn v4`
- Added Support for `pnpm`
- #760
- [#905
](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/905)
- [#14767](https://github.com/postman-eng/postman-app/pull/14767)

[Fix] Added proper installation support for various node package managers

---

codegens/python-http.client/lib/python-httpclient.js
codegens/python-http.client/test/unit/converter.test.js

[Associated Issue](https://github.com/postmanlabs/postman-code-generators/issues/746)
For url using http protocol, python.http-client still generates conn = http.client.HTTPSConnection. Python would throw SSL error when running the script.
Generate the code snippet based on the received url protocol.
Added unit test case.

fix python.http-client generate code snippet using http

---

codegens/curl/lib/index.js
codegens/curl/test/unit/convert.test.js
codegens/python-http.client/test/unit/converter.test.js

This PR fixes issue https://github.com/postmanlabs/postman-app-support/issues/5330.

Added support for usage of --data-binary flag when using long format option for body type binary.

---

npm/deepinstall.js

`pnpm install` from a subproject in a project with a `pnpm-workspace.yaml` installs the workspaces' dependencies, not the subproject even if that subproject is not part of the workspace. That is causing the postinstall script to hang in some cases. This change tells `pnpm` to ignore the parent workspace making it work as expected.
Closes #772 
See: https://github.com/pnpm/pnpm/issues/2412

Update deepinstall.js to fix pnpm install
